export $(grep -v '^#' .env | xargs)
go run main.go \
--PORT=$PORT \
--GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT \
--WV_BEARER_API_KEY=$WV_BEARER_API_KEY \
--WV_PUBLIC_API_URL=$WV_PUBLIC_API_URL \
--UPLOADER_SERVICE_AUTH_HEADER=$UPLOADER_SERVICE_AUTH_HEADER \
--UPLOADER_SERVICE_AUTH_TOKEN=$UPLOADER_SERVICE_AUTH_TOKEN \
--TAG_IDS=$TAG_IDS \
--PRIVACY_IDS=$PRIVACY_IDS \
--SLACK_BEARER_TOKEN=$SLACK_BEARER_TOKEN \
--SLACK_CHANNEL_ID=$SLACK_CHANNEL_ID 
